_base_ = ["insseg-pt-v3m1-0-base.py"]

# Proposed model from docs/mymethod.pdf. Non-model training, data, optimizer,
# scheduler, and evaluation settings are inherited from the PTv3 recipe.
model = dict(
    _delete_=True,
    type="MyMethod-v1m1",
    pt_backbone=dict(
        type="PT-v3m1",
        in_channels=6,
        order=("z", "z-trans", "hilbert", "hilbert-trans"),
        stride=(2, 2, 2, 2),
        enc_depths=(2, 2, 2, 6, 2),
        enc_channels=(32, 64, 128, 256, 512),
        enc_num_head=(2, 4, 8, 16, 32),
        enc_patch_size=(1024, 1024, 1024, 1024, 1024),
        dec_depths=(2, 2, 2, 2),
        dec_channels=(64, 64, 128, 256),
        dec_num_head=(4, 4, 8, 16),
        dec_patch_size=(1024, 1024, 1024, 1024),
        mlp_ratio=4,
        qkv_bias=True,
        qk_scale=None,
        attn_drop=0.0,
        proj_drop=0.0,
        drop_path=0.3,
        pre_norm=True,
        shuffle_orders=True,
        enable_rpe=False,
        enable_flash=True,
        upcast_attention=False,
        upcast_softmax=False,
        cls_mode=False,
    ),
    sp_backbone=dict(
        type="SpUNet-v1m1",
        in_channels=6,
        num_classes=0,
        channels=(32, 64, 128, 256, 256, 128, 96, 96),
        layers=(2, 3, 4, 6, 2, 2, 2, 2),
    ),
    pt_channels=64,
    sp_channels=96,
    fusion_channels=64,
    semantic_num_classes={{ _base_.num_classes }},
    semantic_ignore_index=-1,
    segment_ignore_index={{ _base_.segment_ignore_index }},
    instance_ignore_index=-1,
    cluster_thresh=2.5,
    cluster_closed_points=300,
    cluster_propose_points=50,
    cluster_min_points=10,
    voxel_size={{ _base_.grid_size }},
    semantic_loss_weight=1.0,
    aux_loss_weight=0.4,
    offset_l1_loss_weight=1.0,
    offset_cosine_loss_weight=1.0,
    expert_offset_loss_weight=0.1,
)
