#!/usr/bin/env python3
"""Build a breeding-oriented phenotype-fingerprint figure from predicted traits.

The figure is deliberately descriptive. It converts organ-instance traits into
within-cohort standardized fingerprint axes, but does not infer genetic effects
or breeding value without paired genotype and field-performance records.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch, Rectangle
import numpy as np
import pandas as pd
from PIL import Image
from scipy.stats import theilslopes


RAW_FEATURES = [
    "leaf_count",
    "leaf_area_mesh_surface_mean",
    "leaf_area_mesh_surface_total",
    "leaf_length_mean",
    "petiole_to_leaf_length_ratio",
    "petiole_stem_insertion_angle_mean_deg",
    "leaf_shape_complexity",
    "compactness",
]

FEATURE_LABELS = [
    "Leaf\nnumber",
    "Mean leaf\narea",
    "Total leaf\narea",
    "Mean leaf\nlength",
    "Petiole/leaf\nlength ratio",
    "Petiole--stem\ninsertion angle",
    "Leaf shape\ncomplexity",
    "Canopy\ncompactness",
]

FEATURE_ROW_LABELS = [
    "Leaf number",
    "Mean leaf area",
    "Total leaf area",
    "Mean leaf length",
    "Petiole/leaf\nlength ratio",
    "Mean petiole--stem\ninsertion angle (deg)",
    "Leaf shape\ncomplexity",
    "Canopy compactness",
]

TARGETED_INDEX_LABELS = [
    "Leaf\nexpansion",
    "Organ\nabundance",
    "Leaf shape\ncomplexity",
    "Upper-leaf\nuprightness",
    "Lower-leaf\nopenness",
    "Vertical uprightness\ngradient",
]

ROUND_LEAF_SAMPLES = ["1229no5", "1228no9", "jys167", "zyz39", "jys177"]
FLOWER_LEAF_SAMPLES = ["zyz501H", "jy5231", "jy5225", "zyz39H", "jy5225_1"]
DISPLAY_SAMPLES = ROUND_LEAF_SAMPLES + FLOWER_LEAF_SAMPLES

ROUND_DARK = "#4C8C2B"
ROUND_LIGHT = "#DDEED5"
FLOWER_DARK = "#7B4AA3"
FLOWER_LIGHT = "#E8DDF0"
CARD_EDGE = "#777777"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--traits",
        default="exp/myno2paper/phenotype_demo_mymethod_fig11_pred_effective/plant_traits.tsv",
        help="TSV generated by derive_traits_from_mymethod.py.",
    )
    parser.add_argument(
        "--output-dir",
        default="exp/myno2paper/phenotype_demo_mymethod_fig11_pred_effective",
        help="Directory for source tables.",
    )
    parser.add_argument(
        "--figure-stem",
        default="outputs/fig11_trait_fingerprint",
        help="Figure path without extension.",
    )
    parser.add_argument(
        "--leaf-traits",
        default="exp/myno2paper/phenotype_demo_mymethod_fig11_pred_effective/leaf_traits.tsv",
        help="Leaf-level trait TSV generated from predicted point-cloud instances.",
    )
    parser.add_argument(
        "--posture-traits",
        default="exp/myno2paper/phenotype_demo_mymethod_fig11_pred_effective/leaf_posture_traits.tsv",
        help="Leaf effective-posture TSV generated from predicted point-cloud instances.",
    )
    parser.add_argument(
        "--indices-output",
        default="outputs/plant_targeted_phenotype_indices.csv",
        help="CSV path for the plant-level targeted phenotype indices.",
    )
    parser.add_argument(
        "--effective-posture-output",
        default="outputs/leaf_effective_posture_traits.csv",
        help="CSV path for leaf-level effective-posture results.",
    )
    parser.add_argument(
        "--source",
        choices=("mymethod_prediction", "gt_annotation_proxy"),
        default="mymethod_prediction",
        help="Trait-record source used to calculate the figure.",
    )
    return parser.parse_args()


def zscore(frame: pd.DataFrame) -> pd.DataFrame:
    std = frame.std(axis=0, ddof=0).replace(0, 1.0)
    return (frame - frame.mean(axis=0)) / std


def resolve_project_path(path_value: str) -> Path:
    """Resolve defaults from either the project root or the Pointcept subdirectory."""
    candidate = Path(path_value)
    if candidate.exists() or candidate.is_absolute():
        return candidate
    project_root = Path(__file__).resolve().parents[3]
    return project_root / candidate


def leaf_type(sample: str) -> str:
    return "Round-leaf" if sample in ROUND_LEAF_SAMPLES else "Lobed-leaf"


def derive_targeted_indices(
    plant_traits: pd.DataFrame,
    leaf_traits: pd.DataFrame,
    posture_traits: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Compute targeted indices from predicted local insertion and whole-leaf posture."""
    valid_leaf = leaf_traits.copy()
    valid_leaf["leaf_shape_complexity"] = (
        valid_leaf["leaf_perimeter"] ** 2
        / (4 * np.pi * valid_leaf["leaf_area_mesh_surface"])
    )
    valid_leaf = valid_leaf.loc[
        np.isfinite(valid_leaf["leaf_perimeter"])
        & np.isfinite(valid_leaf["leaf_area_mesh_surface"])
        & (valid_leaf["leaf_perimeter"] > 0)
        & (valid_leaf["leaf_area_mesh_surface"] > 0)
        & np.isfinite(valid_leaf["leaf_shape_complexity"])
    ].copy()
    valid_leaf["leaf_type"] = valid_leaf["sample"].map(leaf_type)
    leaf_shape = valid_leaf.groupby("sample")["leaf_shape_complexity"].median()

    profiles = []
    posture_metrics = pd.DataFrame(
        index=plant_traits.index,
        columns=[
            "upper_leaf_uprightness",
            "middle_leaf_uprightness",
            "lower_leaf_openness",
            "vertical_uprightness_gradient",
            "mean_leaf_droop_index",
        ],
        dtype=float,
    )
    for sample in plant_traits.index:
        plant_posture = posture_traits.loc[posture_traits["sample"] == sample].copy()
        plant_posture = plant_posture.loc[
            np.isfinite(plant_posture["leaf_insertion_height"])
            & np.isfinite(plant_posture["effective_leaf_uprightness"])
        ].copy()
        if plant_posture.empty:
            continue
        height_min = plant_posture["leaf_insertion_height"].min()
        height_range = plant_posture["leaf_insertion_height"].max() - height_min
        if not np.isfinite(height_range) or height_range <= 0:
            continue
        plant_posture["normalized_insertion_height"] = (
            plant_posture["leaf_insertion_height"] - height_min
        ) / height_range
        plant_posture = plant_posture.sort_values("normalized_insertion_height").reset_index(drop=True)
        plant_posture["sample"] = sample
        plant_posture["leaf_type"] = leaf_type(sample)
        profiles.append(plant_posture)

        n_leaves = len(plant_posture)
        lower, middle, upper = np.array_split(np.arange(n_leaves), 3)
        uprightness = plant_posture["effective_leaf_uprightness"]
        # 1 - U_eff may exceed one when a lower leaf extends downward; this is intentional.
        posture_metrics.loc[sample, "upper_leaf_uprightness"] = uprightness.iloc[upper].mean()
        posture_metrics.loc[sample, "middle_leaf_uprightness"] = uprightness.iloc[middle].mean()
        posture_metrics.loc[sample, "lower_leaf_openness"] = (1 - uprightness.iloc[lower]).mean()
        posture_metrics.loc[sample, "mean_leaf_droop_index"] = plant_posture["leaf_droop_index"].mean()
        if n_leaves >= 3 and plant_posture["normalized_insertion_height"].nunique() >= 2:
            posture_metrics.loc[sample, "vertical_uprightness_gradient"] = float(
                theilslopes(
                    uprightness.to_numpy(),
                    plant_posture["normalized_insertion_height"].to_numpy(),
                )[0]
            )

    profile_frame = pd.concat(profiles, ignore_index=True) if profiles else pd.DataFrame()
    targeted_raw = pd.DataFrame(index=plant_traits.index)
    base_standardized = zscore(plant_traits)
    targeted_raw["leaf_expansion"] = base_standardized[
        ["leaf_area_mesh_surface_mean", "leaf_area_mesh_surface_total", "leaf_length_mean"]
    ].mean(axis=1)
    targeted_raw["organ_abundance"] = base_standardized["leaf_count"]
    targeted_raw["leaf_shape_complexity"] = leaf_shape.reindex(plant_traits.index)
    targeted_raw = targeted_raw.join(
        posture_metrics[["upper_leaf_uprightness", "lower_leaf_openness", "vertical_uprightness_gradient"]]
    )
    targeted_z = zscore(targeted_raw)
    return targeted_raw, targeted_z, valid_leaf, profile_frame, posture_metrics


def add_card(fig: plt.Figure, subplot_spec) -> mpl.transforms.Bbox:
    """Add a restrained rounded frame behind one of the four content panels."""
    position = subplot_spec.get_position(fig)
    inset = 0.0035
    card = FancyBboxPatch(
        (position.x0 + inset, position.y0 + inset),
        position.width - 2 * inset,
        position.height - 2 * inset,
        boxstyle="round,pad=0.004,rounding_size=0.008",
        transform=fig.transFigure,
        facecolor="white",
        edgecolor=CARD_EDGE,
        linewidth=0.8,
        zorder=-5,
        clip_on=False,
    )
    fig.add_artist(card)
    return position


def add_panel_header(fig: plt.Figure, position: mpl.transforms.Bbox, label: str, title: str) -> None:
    fig.text(
        position.x0 + 0.020 * position.width,
        position.y1 - 0.034 * position.height,
        label,
        ha="left",
        va="top",
        fontsize=16,
        fontweight="bold",
    )
    fig.text(
        position.x0 + 0.545 * position.width,
        position.y1 - 0.036 * position.height,
        title,
        ha="center",
        va="top",
        fontsize=13.4,
        fontweight="bold",
    )


def draw_workflow(ax: plt.Axes) -> None:
    ax.set_axis_off()
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    boxes = [
        (0.09, 0.856, "3D point cloud\nacquisition", "#DCEBF3"),
        (0.09, 0.677, "Instance segmentation\n& trait extraction", "#E5F0DF"),
        (0.09, 0.498, "Standardized trait vector\n(8 descriptor axes)", "#F7E9C9"),
        (0.09, 0.319, "Phenotype fingerprint\n(6 targeted indices)", "#F3DFE7"),
        (0.09, 0.140, "Agronomically targeted\nphenotype profiles", "#E4EAF6"),
    ]
    width, height = 0.82, 0.112
    for x, y, text, color in boxes:
        ax.add_patch(
            FancyBboxPatch(
                (x, y),
                width,
                height,
                boxstyle="round,pad=0.012,rounding_size=0.035",
                facecolor=color,
                edgecolor="#666666",
                linewidth=0.8,
            )
        )
        ax.text(x + width / 2, y + height / 2, text, ha="center", va="center", fontsize=9.4, fontweight="bold")
    for _, y, _, _ in boxes[:-1]:
        ax.add_patch(
            FancyArrowPatch(
                (0.50, y),
                (0.50, y - 0.052),
                arrowstyle="-|>",
                mutation_scale=11,
                linewidth=0.8,
                color="#666666",
            )
        )

    legend_y = 0.045
    ax.add_patch(FancyBboxPatch((0.09, 0.010), 0.82, 0.084, boxstyle="round,pad=0.012,rounding_size=0.028",
                                facecolor="white", edgecolor="#777777", linewidth=0.7))
    ax.scatter(0.22, legend_y + 0.023, s=65, color=ROUND_DARK, edgecolor="#333333", linewidth=0.5, zorder=3)
    ax.text(0.33, legend_y + 0.023, "Round-leaf", ha="left", va="center", fontsize=9.0)
    ax.scatter(0.22, legend_y - 0.020, s=65, color=FLOWER_DARK, edgecolor="#333333", linewidth=0.5, zorder=3)
    ax.text(0.33, legend_y - 0.020, "Lobed-leaf", ha="left", va="center", fontsize=9.0)


def draw_matrix(
    ax: plt.Axes,
    values: pd.DataFrame,
    xlabels: list[str],
    ylabels: list[str],
    cmap: LinearSegmentedColormap,
    *,
    cell_fontsize: float = 8.0,
    row_group_boundary: int | None = None,
    column_group_boundary: int | None = None,
) -> mpl.image.AxesImage:
    limit = max(2.2, float(np.nanmax(np.abs(values.to_numpy()))) + 0.1)
    image = ax.imshow(values.to_numpy(), aspect="auto", cmap=cmap, vmin=-limit, vmax=limit)
    ax.set_xticks(np.arange(values.shape[1]), xlabels)
    ax.set_yticks(np.arange(values.shape[0]), ylabels)
    ax.tick_params(length=0, pad=4)
    for x in np.arange(-0.5, values.shape[1], 1):
        ax.axvline(x, color="white", lw=0.5)
    for y in np.arange(-0.5, values.shape[0], 1):
        ax.axhline(y, color="white", lw=0.5)
    if row_group_boundary is not None:
        ax.axhline(row_group_boundary - 0.5, color="#4D5963", lw=1.2)
    if column_group_boundary is not None:
        ax.axvline(column_group_boundary - 0.5, color="#4D5963", lw=1.2)
    for row in range(values.shape[0]):
        for col in range(values.shape[1]):
            value = values.iloc[row, col]
            ax.text(
                col,
                row,
                f"{value:.1f}",
                ha="center",
                va="center",
                fontsize=cell_fontsize,
                color="white" if abs(value) >= 1.25 else "#20262B",
            )
    return image


def add_column_group_labels(ax: plt.Axes) -> None:
    for start, end, label, color in [(-0.5, 4.5, "Round-leaf", ROUND_DARK), (4.5, 9.5, "Lobed-leaf", FLOWER_DARK)]:
        transform = ax.get_xaxis_transform()
        ax.plot([start, end], [1.08, 1.08], color=color, lw=1.2, transform=transform, clip_on=False)
        ax.plot([start, start], [1.08, 1.03], color=color, lw=1.2, transform=transform, clip_on=False)
        ax.plot([end, end], [1.08, 1.03], color=color, lw=1.2, transform=transform, clip_on=False)
        ax.text((start + end) / 2, 1.16, label, color=color, ha="center", va="bottom", fontsize=9.2,
                fontweight="bold", transform=transform, clip_on=False)


def draw_leaf_shape_complexity(ax: plt.Axes, leaf_traits: pd.DataFrame) -> None:
    groups = ["Round-leaf", "Lobed-leaf"]
    dark_colors = [ROUND_DARK, FLOWER_DARK]
    light_colors = [ROUND_LIGHT, FLOWER_LIGHT]
    values = [
        leaf_traits.loc[leaf_traits["leaf_type"] == group, "leaf_shape_complexity"].groupby(
            leaf_traits.loc[leaf_traits["leaf_type"] == group, "sample"]
        ).median().to_numpy()
        for group in groups
    ]
    jitter_rng = np.random.default_rng(42)
    summary_width = 0.28
    for position, (group_values, color) in enumerate(zip(values, dark_colors)):
        q1, median, q3 = np.percentile(group_values, [25, 50, 75])
        group_min, group_max = np.min(group_values), np.max(group_values)
        ax.vlines(position, group_min, group_max, color=color, linewidth=0.8, alpha=0.75, zorder=1)
        ax.add_patch(
            Rectangle(
                (position - summary_width / 2, q1),
                summary_width,
                q3 - q1,
                facecolor=light_colors[position],
                edgecolor=color,
                linewidth=1.05,
                zorder=2,
            )
        )
        ax.hlines(median, position - summary_width / 2, position + summary_width / 2,
                  color="#333333", linewidth=1.8, zorder=4)
        jitter = jitter_rng.uniform(-0.08, 0.08, size=len(group_values))
        ax.scatter(position + jitter, group_values, s=32, color=color, edgecolor="#222222", linewidth=0.45, zorder=5)
    ax.set_xlim(-0.5, 1.5)
    ax.set_xticks([0, 1], ["Round-leaf\n(n = 5)", "Lobed-leaf\n(n = 5)"], fontsize=8.2)
    ax.set_ylabel("Leaf shape complexity index,\n" + r"$P^2/(4\pi A)$", fontsize=8.8)
    ax.set_title("c1. Leaf shape complexity", fontsize=10.4, loc="left", pad=8, fontweight="bold")
    ax.tick_params(axis="y", labelsize=8.0, length=2)
    ax.grid(axis="y", color="#D5DADD", lw=0.55, zorder=0)


def draw_vertical_posture_profile(
    ax: plt.Axes,
    profiles: pd.DataFrame,
) -> None:
    """Plot all plants together without group-wise interpolation or smoothing."""
    individual_colors = {
        "Round-leaf": ["#4C8C2B", "#5E9E39", "#3D7A28", "#72A94B", "#2F6E25"],
        "Lobed-leaf": ["#7B4AA3", "#8E61B0", "#69408F", "#9C73BF", "#5F3781"],
    }
    markers = {"Round-leaf": "o", "Lobed-leaf": "s"}
    for group in ("Round-leaf", "Lobed-leaf"):
        group_profiles = profiles.loc[profiles["leaf_type"] == group]
        for plant_index, (_, plant_profile) in enumerate(group_profiles.groupby("sample")):
            plant_profile = plant_profile.sort_values("normalized_insertion_height")
            ax.plot(
                plant_profile["normalized_insertion_height"],
                plant_profile["effective_posture_angle_deg"],
                color=individual_colors[group][plant_index],
                alpha=0.76,
                lw=1.2,
                marker=markers[group],
                markersize=2.8,
                markerfacecolor="white",
                markeredgewidth=0.75,
                markeredgecolor=individual_colors[group][plant_index],
                zorder=2,
                clip_on=False,
            )
    # Preserve complete endpoint markers at normalized heights 0 and 1.
    ax.set_xlim(-0.055, 1.055)
    ax.set_xticks(np.linspace(0, 1, 6))
    ax.set_ylim(0, 180)
    ax.tick_params(labelsize=7.3, length=2)
    ax.grid(color="#D5DADD", lw=0.55)
    ax.set_title("c2. Vertical effective leaf-posture profiles", fontsize=9.3, loc="left", pad=8, fontweight="bold")
    ax.set_xlabel("Normalized leaf insertion height", fontsize=8.3, labelpad=7)
    ax.set_ylabel("Effective leaf posture angle (deg)", fontsize=8.0, labelpad=5)


def crop_rgb_canvas(image: np.ndarray) -> np.ndarray:
    """Remove the empty viewport around an RGB point cloud without clipping it."""
    rgb = image[..., :3]
    white_threshold = 245 / 255 if np.issubdtype(rgb.dtype, np.floating) else 245
    occupied = np.any(rgb < white_threshold, axis=2)
    rows, columns = np.where(occupied)
    if rows.size == 0:
        return image

    pad = max(16, int(0.06 * max(np.ptp(rows) + 1, np.ptp(columns) + 1)))
    y0 = max(0, rows.min() - pad)
    y1 = min(image.shape[0], rows.max() + pad + 1)
    x0 = max(0, columns.min() - pad)
    x1 = min(image.shape[1], columns.max() + pad + 1)
    return image[y0:y1, x0:x1]


def draw_rgb_inputs(fig: plt.Figure, position: mpl.transforms.Bbox, samples: list[str], figure_dir: Path) -> None:
    add_panel_header(fig, position, "a", "3D point clouds of representative plants")
    content_x0 = position.x0 + 0.035 * position.width
    content_width = 0.930 * position.width
    content_y0 = position.y0 + 0.045 * position.height
    content_height = 0.790 * position.height
    group_gap = 0.075 * content_height
    group_height = (content_height - group_gap) / 2
    groups = [
        ("Round-leaf", ROUND_DARK, ROUND_LIGHT, content_y0 + group_height + group_gap, samples[:5]),
        ("Lobed-leaf", FLOWER_DARK, FLOWER_LIGHT, content_y0, samples[5:]),
    ]
    for label, dark, light, group_y, group_samples in groups:
        group_box = FancyBboxPatch(
            (content_x0, group_y),
            content_width,
            group_height,
            boxstyle="round,pad=0.003,rounding_size=0.008",
            transform=fig.transFigure,
            facecolor="white",
            edgecolor=dark,
            linewidth=1.0,
            zorder=-2,
        )
        fig.add_artist(group_box)
        pill_width = 0.17 * content_width
        pill = FancyBboxPatch(
            (content_x0 + 0.012 * content_width, group_y + group_height - 0.006 * position.height),
            pill_width,
            0.060 * position.height,
            boxstyle="round,pad=0.003,rounding_size=0.006",
            transform=fig.transFigure,
            facecolor=dark,
            edgecolor=dark,
            linewidth=0,
            zorder=4,
        )
        fig.add_artist(pill)
        fig.text(content_x0 + 0.012 * content_width + pill_width / 2, group_y + group_height + 0.023 * position.height,
                 label, color="white", ha="center", va="center", fontsize=8.6, fontweight="bold", zorder=5)

        cell_width = content_width / 5
        for col, sample in enumerate(group_samples):
            image_x = content_x0 + col * cell_width + 0.035 * cell_width
            image_y = group_y + 0.150 * group_height
            image_width = 0.930 * cell_width
            image_height = 0.730 * group_height
            ax = fig.add_axes((image_x, image_y, image_width, image_height), zorder=1)
            matches = sorted(figure_dir.glob(f"{sample}_*_rgb_viewport_*.png"))
            if not matches:
                raise FileNotFoundError(f"No RGB point-cloud screenshot found for {sample}.")
            ax.imshow(crop_rgb_canvas(plt.imread(matches[-1])), interpolation="none")
            ax.set_axis_off()
            fig.text(image_x + image_width / 2, group_y + 0.060 * group_height, sample,
                     ha="center", va="center", fontsize=8.4)


def main() -> None:
    args = parse_args()
    traits_path = resolve_project_path(args.traits)
    leaf_traits_path = resolve_project_path(args.leaf_traits)
    posture_traits_path = resolve_project_path(args.posture_traits)
    output_dir = resolve_project_path(args.output_dir)
    figure_stem = resolve_project_path(args.figure_stem)
    indices_output = resolve_project_path(args.indices_output)
    effective_posture_output = resolve_project_path(args.effective_posture_output)
    output_dir.mkdir(parents=True, exist_ok=True)
    figure_stem.parent.mkdir(parents=True, exist_ok=True)

    trait_table = pd.read_csv(traits_path, sep="\t")
    leaf_table = pd.read_csv(leaf_traits_path, sep="\t")
    posture_table = pd.read_csv(posture_traits_path, sep="\t")
    selected = trait_table.loc[trait_table["source"] == args.source].copy()
    leaf_table = leaf_table.loc[leaf_table["source"] == args.source].copy()
    posture_table = posture_table.loc[posture_table["source"] == args.source].copy()
    if selected.empty:
        raise ValueError(f"No rows with source={args.source} were found.")
    required_plant_features = sorted(set(RAW_FEATURES) - {"leaf_shape_complexity"})
    missing = sorted(set(required_plant_features) - set(selected.columns))
    if missing:
        raise ValueError(f"Missing fingerprint features: {missing}")
    missing_leaf = sorted({"sample", "leaf_perimeter", "leaf_area_mesh_surface"} - set(leaf_table.columns))
    missing_posture = sorted(
        {
            "sample",
            "leaf_insertion_height",
            "petiole_stem_angle_deg",
            "effective_leaf_uprightness",
            "leaf_droop_index",
            "posture_method",
        } - set(posture_table.columns)
    )
    if missing_leaf or missing_posture:
        raise ValueError(
            f"Missing required leaf/posture fields. leaf={missing_leaf}; posture={missing_posture}"
        )

    selected = selected.set_index("sample")
    missing_samples = [sample for sample in DISPLAY_SAMPLES if sample not in selected.index]
    if missing_samples:
        raise ValueError(f"Missing Fig. 11 samples from the trait table: {missing_samples}")
    plant_traits = selected.loc[DISPLAY_SAMPLES, required_plant_features].astype(float)
    targeted_raw, targeted_indices, valid_leaf_traits, posture_profiles, posture_summary = derive_targeted_indices(
        plant_traits, leaf_table, posture_table
    )
    missing_targeted = targeted_raw.index[targeted_raw.isna().any(axis=1)].tolist()
    if missing_targeted:
        raise ValueError(f"Missing valid targeted phenotype measurements for: {missing_targeted}")
    for sample in plant_traits.index:
        profile = posture_profiles.loc[posture_profiles["sample"] == sample]
        methods = profile["posture_method"].value_counts().to_dict()
        layers = profile["canopy_layer"].value_counts().to_dict()
        theta = profile["petiole_stem_angle_deg"].to_numpy(dtype=float)
        uprightness = profile["effective_leaf_uprightness"].to_numpy(dtype=float)
        droop = profile["leaf_droop_index"].to_numpy(dtype=float)
        gradient = posture_summary.loc[sample, "vertical_uprightness_gradient"]
        print(
            f"[effective posture] {sample}: valid_leaves={len(profile)}, methods={methods}, "
            f"theta_ins={np.nanmin(theta):.2f}..{np.nanmax(theta):.2f}, "
            f"U_eff={np.nanmin(uprightness):.3f}..{np.nanmax(uprightness):.3f}, "
            f"droop={np.nanmin(droop):.3f}..{np.nanmax(droop):.3f}, "
            f"Theil-Sen={gradient:.4f}, layers={layers}",
            flush=True,
        )

    def group_sorted(samples: list[str]) -> list[str]:
        return sorted(
            samples,
            key=lambda sample: targeted_raw.loc[sample, "vertical_uprightness_gradient"],
            reverse=True,
        )

    display_order = group_sorted(ROUND_LEAF_SAMPLES) + group_sorted(FLOWER_LEAF_SAMPLES)
    plant_traits = plant_traits.loc[display_order]
    targeted_raw = targeted_raw.loc[display_order]
    targeted_indices = targeted_indices.loc[display_order]
    posture_summary = posture_summary.loc[display_order]
    raw = plant_traits.copy()
    raw["leaf_shape_complexity"] = targeted_raw["leaf_shape_complexity"]
    raw = raw[RAW_FEATURES]
    standardized = zscore(raw)
    source_data = pd.DataFrame(index=raw.index)
    source_data.insert(0, "plant_id", source_data.index)
    source_data.insert(1, "leaf_type", [leaf_type(sample) for sample in source_data.index])
    source_data = source_data.join(posture_summary).join(raw.add_prefix("raw_b_")).join(
        standardized.add_prefix("z_b_")
    ).join(targeted_raw.add_prefix("raw_targeted_")).join(targeted_indices.add_prefix("z_targeted_"))
    indices_output.parent.mkdir(parents=True, exist_ok=True)
    source_data.to_csv(indices_output, index=False, float_format="%.6f")
    effective_posture_output.parent.mkdir(parents=True, exist_ok=True)
    posture_profiles.rename(
        columns={
            "sample": "plant_id",
            "leaf_instance_id": "leaf_id",
            "leaf_insertion_height": "insertion_height",
            "petiole_stem_angle_deg": "petiole_stem_insertion_angle_deg",
        }
    ).to_csv(effective_posture_output, index=False, float_format="%.6f")

    mpl.rcParams.update(
        {
            "font.family": "Times New Roman",
            "font.serif": ["Times New Roman", "Times", "DejaVu Serif", "serif"],
            "font.sans-serif": ["Arial", "Helvetica", "DejaVu Sans", "sans-serif"],
            "font.size": 6.5,
            "svg.fonttype": "none",
            "pdf.fonttype": 42,
            "axes.linewidth": 0.7,
            "axes.spines.right": False,
            "axes.spines.top": False,
        }
    )
    cmap = LinearSegmentedColormap.from_list("fingerprint", ["#2F66A3", "#FAFAF8", "#C7443E"])
    fig = plt.figure(figsize=(15.5, 10.3), facecolor="white")
    outer = fig.add_gridspec(
        1,
        2,
        width_ratios=[0.145, 0.855],
        wspace=0.025,
        left=0.026,
        right=0.982,
        bottom=0.040,
        top=0.966,
    )
    ax_workflow = fig.add_subplot(outer[0, 0])
    draw_workflow(ax_workflow)

    right_grid = outer[0, 1].subgridspec(
        2,
        2,
        width_ratios=[1.05, 1.00],
        height_ratios=[1.00, 1.00],
        wspace=0.045,
        hspace=0.065,
    )
    a_spec, b_spec = right_grid[0, 0], right_grid[0, 1]
    c_spec, d_spec = right_grid[1, 0], right_grid[1, 1]
    a_position = add_card(fig, a_spec)
    b_position = add_card(fig, b_spec)
    c_position = add_card(fig, c_spec)
    d_position = add_card(fig, d_spec)

    draw_rgb_inputs(fig, a_position, raw.index.tolist(), figure_stem.parent)

    add_panel_header(fig, b_position, "b", "Eight standardized quantitative traits")
    fig.text(
        b_position.x0 + 0.545 * b_position.width,
        b_position.y1 - 0.083 * b_position.height,
        "(within-set z score)",
        ha="center",
        va="top",
        fontsize=10.0,
    )
    b_heatmap_position = [
        b_position.x0 + 0.195 * b_position.width,
        b_position.y0 + 0.192 * b_position.height,
        0.750 * b_position.width,
        0.555 * b_position.height,
    ]
    ax_b = fig.add_axes(b_heatmap_position)
    b_values = standardized.T.loc[RAW_FEATURES, raw.index]
    heatmap = draw_matrix(
        ax_b,
        b_values,
        raw.index.tolist(),
        FEATURE_ROW_LABELS,
        cmap,
        cell_fontsize=7.7,
        column_group_boundary=len(ROUND_LEAF_SAMPLES),
    )
    ax_b.tick_params(axis="x", top=True, bottom=False, labeltop=True, labelbottom=False, pad=5, labelsize=7.5)
    ax_b.tick_params(axis="y", labelsize=8.0)
    ax_b.set_ylim(len(FEATURE_ROW_LABELS) - 0.5, -0.5)
    add_column_group_labels(ax_b)
    b_cax = fig.add_axes([
        b_heatmap_position[0],
        b_position.y0 + 0.085 * b_position.height,
        b_heatmap_position[2],
        0.026 * b_position.height,
    ])
    b_cbar = fig.colorbar(heatmap, cax=b_cax, orientation="horizontal", extend="both")
    b_cbar.set_label("Standardized trait value (z score)", fontsize=8.7, labelpad=3)
    b_cbar.ax.tick_params(labelsize=7.7, length=2)

    add_panel_header(fig, c_position, "c", "Leaf morphology and vertical effective-posture profiles")
    c_inner_x = c_position.x0 + 0.090 * c_position.width
    c_inner_y = c_position.y0 + 0.165 * c_position.height
    c_inner_width = 0.855 * c_position.width
    c_inner_height = 0.650 * c_position.height
    c_gap = 0.100 * c_inner_width
    c1_width = 0.42 * (c_inner_width - c_gap)
    c2_width = (c_inner_width - c_gap) - c1_width
    ax_c1 = fig.add_axes((c_inner_x, c_inner_y, c1_width, c_inner_height))
    c2_x = c_inner_x + c1_width + c_gap
    ax_c2 = fig.add_axes((c2_x, c_inner_y, c2_width, c_inner_height))
    draw_leaf_shape_complexity(ax_c1, valid_leaf_traits)
    draw_vertical_posture_profile(ax_c2, posture_profiles)

    add_panel_header(
        fig,
        d_position,
        "d",
        "Agronomically targeted phenotype fingerprint",
    )
    fig.text(
        d_position.x0 + 0.545 * d_position.width,
        d_position.y1 - 0.083 * d_position.height,
        "(within-set z score; n = 10 plants)",
        ha="center",
        va="top",
        fontsize=10.0,
    )
    d_heatmap_position = [
        d_position.x0 + 0.195 * d_position.width,
        d_position.y0 + 0.185 * d_position.height,
        0.750 * d_position.width,
        0.570 * d_position.height,
    ]
    ax_d = fig.add_axes(d_heatmap_position)
    d_values = targeted_indices.T.loc[targeted_indices.columns, raw.index]
    index_heatmap = draw_matrix(
        ax_d,
        d_values,
        raw.index.tolist(),
        TARGETED_INDEX_LABELS,
        cmap,
        cell_fontsize=8.0,
        column_group_boundary=len(ROUND_LEAF_SAMPLES),
    )
    ax_d.tick_params(axis="x", top=True, bottom=False, labeltop=True, labelbottom=False, pad=5, labelsize=7.5)
    ax_d.tick_params(axis="y", labelsize=8.0)
    add_column_group_labels(ax_d)
    d_cax = fig.add_axes([
        d_heatmap_position[0],
        d_position.y0 + 0.082 * d_position.height,
        d_heatmap_position[2],
        0.026 * d_position.height,
    ])
    d_cbar = fig.colorbar(index_heatmap, cax=d_cax, orientation="horizontal", extend="both")
    d_cbar.set_label("Standardized index score", fontsize=8.7, labelpad=3)
    d_cbar.ax.tick_params(labelsize=7.7, length=2)

    png_path = figure_stem.with_suffix(".png")
    fig.savefig(figure_stem.with_suffix(".pdf"), dpi=600, bbox_inches="tight")
    fig.savefig(png_path, dpi=600, bbox_inches="tight")
    with Image.open(png_path) as image:
        image.convert("RGB").save(figure_stem.with_suffix(".bmp"))
    fig.savefig(figure_stem.with_suffix(".svg"), bbox_inches="tight")
    plt.close(fig)


if __name__ == "__main__":
    main()
